### ISSUE TITLE
ERROR  TypeError: Cannot read property 'get' of undefined from webpack

### ISSUE THREAD

**Issue by muzig1** [vueComponent/ant-design-vue-pro#1148]
**Question （问题描述）**

 ERROR  TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
    at /Users/xxx/src/xxx/c5/vgs/node_modules/_webpack@5.28.0@webpack/lib/DefinePlugin.js:549:57
    at Array.forEach (<anonymous>)
    at walkDefinitionsForValues (/Users/xxx/src/xxx/c5/vgs/node_modules/_webpack@5.28.0@webpack/lib/DefinePlugin.js:545:31)
    at /Users/xxx/src/xxx/c5/vgs/node_modules/_webpack@5.28.0@webpack/lib/DefinePlugin.js:571:5
    at SyncHook.eval [as call] (eval at create (/Users/xxx/src/xxx/c5/vgs/node_modules/_tapable@1.1.3@tapable/lib/HookCodeFactory.js:19:10), <anonymous>:21:1)
    at SyncHook.lazyCompileHook (/Users/xxx/src/xxx/c5/vgs/node_modules/_tapable@1.1.3@tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/xxx/src/xxx/c5/vgs/node_modules/_webpack@4.46.0@webpack/lib/Compiler.js:631:26)
    at /Users/xxx/src/xxx/c5/vgs/node_modules/_webpack@4.46.0@webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/xxx/src/xxx/c5/vgs/node_modules/_tapable@1.1.3@tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/xxx/src/xxx/c5/vgs/node_modules/_tapable@1.1.3@tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/xxx/src/xxx/c5/vgs/node_modules/_webpack@4.46.0@webpack/lib/Compiler.js:662:28)
    at /Users/xxx/src/xxx/c5/vgs/node_modules/_webpack@4.46.0@webpack/lib/Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/xxx/src/xxx/c5/vgs/node_modules/_tapable@1.1.3@tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/xxx/src/xxx/c5/vgs/node_modules/_tapable@1.1.3@tapable/lib/Hook.js:154:20)
    at Watching._go (/Users/xxx/src/xxx/c5/vgs/node_modules/_webpack@4.46.0@webpack/lib/Watching.js:41:32)
    at /Users/xxx/src/xxx/c5/vgs/node_modules/_webpack@4.46.0@webpack/lib/Watching.js:33:9

**Describe the solution you'd like （你期待的是什么？）**

How to fix it.

**Additional context（附加信息）**

**Comment by muzig1** [comment]
目前的处理办法是: cnpm i --save webpack@4.45.0

感谢

**Comment by watdenson** [comment]
> 目前的处理办法是: cnpm i --save webpack@4.45.0
> 
> 感谢

为什么是4.45.0，不是4.46.0

**Comment by muzig1** [comment]
> > 目前的处理办法是: cnpm i --save webpack@4.45.0
> > 感谢
> 
> 为什么是4.45.0，不是4.46.0

我一个一个试的; 有一个OK, 就没有处理了.
不过之前留意到官方提到, 建议使用yarn去管理, 因为npm会存在版本问题, 一劳永逸还是采用yarn去管理项目.
