### ISSUE TITLE
npm run serve 报错

### ISSUE THREAD

**Issue by xiaobo1215** [vueComponent/ant-design-vue-pro#1243]
dependencies
at exports.provide (E:\demo\ant-design-vue-pro\my-project\node_modules\_webpack@5.52.0@webpack\lib\util\MapHelpers.js:17:20)
    at E:\demo\ant-design-vue-pro\my-project\node_modules\_webpack@5.52.0@webpack\lib\DefinePlugin.js:290:6
    at SyncHook.eval [as call] (eval at create (E:\demo\ant-design-vue-pro\my-project\node_modules\_tapable@1.1.3@tapable\lib\HookCodeFactory.js:19:10), <anonymous>:21:1)
    at SyncHook.lazyCompileHook (E:\demo\ant-design-vue-pro\my-project\node_modules\_tapable@1.1.3@tapable\lib\Hook.js:154:20)
    at Compiler.newCompilation (E:\demo\ant-design-vue-pro\my-project\node_modules\_webpack@4.46.0@webpack\lib\Compiler.js:631:26)
    at E:\demo\ant-design-vue-pro\my-project\node_modules\_webpack@4.46.0@webpack\lib\Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\demo\ant-design-vue-pro\my-project\node_modules\_tapable@1.1.3@tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (E:\demo\ant-design-vue-pro\my-project\node_modules\_tapable@1.1.3@tapable\lib\Hook.js:154:20)
    at Compiler.compile (E:\demo\ant-design-vue-pro\my-project\node_modules\_webpack@4.46.0@webpack\lib\Compiler.js:662:28)
    at E:\demo\ant-design-vue-pro\my-project\node_modules\_webpack@4.46.0@webpack\lib\Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\demo\ant-design-vue-pro\my-project\node_modules\_tapable@1.1.3@tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (E:\demo\ant-design-vue-pro\my-project\node_modules\_tapable@1.1.3@tapable\lib\Hook.js:154:20)
    at Watching._go (E:\demo\ant-design-vue-pro\my-project\node_modules\_webpack@4.46.0@webpack\lib\Watching.js:41:32)
    at E:\demo\ant-design-vue-pro\my-project\node_modules\_webpack@4.46.0@webpack\lib\Watching.js:33:9
    at Compiler.readRecords (E:\demo\ant-design-vue-pro\my-project\node_modules\_webpack@4.46.0@webpack\lib\Compiler.js:529

**Comment by xiaobo1215** [comment]
在 package.json dependencies中 增加 "webpack":"^4.46.0" ，报错解决

**Comment by xueluhan** [comment]
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'F:\项目文件\my-project\node_modules\_@vue_cli-service@4.5.13@@vue\cli-service\bin\vue-cli-service.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-antd-pro@3.0.2 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-antd-pro@3.0.2 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
