### ISSUE TITLE
run serve报错

### ISSUE THREAD

**Issue by pandaymx** [vueComponent/ant-design-vue-pro#1442]
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
 INFO  Starting development server...
[51%] building (824/1568 modules)
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
[95%] emitting (emit ThemeColorReplacer)
Extracted theme color css content length: 28771
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at getHash (E:\vue\my-project\node_modules\.pnpm\webpack-theme-color-replacer@1.4.1\node_modules\webpack-theme-color-replacer\src\replaceFileName.js:17:21)
    at replaceFileName (E:\vue\my-project\node_modules\.pnpm\webpack-theme-color-replacer@1.4.1\node_modules\webpack-theme-color-replacer\src\replaceFileName.js:10:68)
    at getFileName (E:\vue\my-project\node_modules\.pnpm\webpack-theme-color-replacer@1.4.1\node_modules\webpack-theme-color-replacer\src\Handler.js:34:40)
    at Handler.handle (E:\vue\my-project\node_modules\.pnpm\webpack-theme-color-replacer@1.4.1\node_modules\webpack-theme-color-replacer\src\Handler.js:24:26)
    at E:\vue\my-project\node_modules\.pnpm\webpack-theme-color-replacer@1.4.1\node_modules\webpack-theme-color-replacer\src\index.js:28:26
    at Hook.eval [as callAsync] (eval at create (E:\vue\my-project\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:14:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\vue\my-project\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.emitAssets (E:\vue\my-project\node_modules\.pnpm\webpack@5.74.0\node_modules\webpack\lib\Compiler.js:891:19) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by edWin-m** [comment]
@pandaymx If you are still facing this issue try enabling the legacy OpenSSL provider.

```shell
export NODE_OPTIONS=--openssl-legacy-provider
```

**Comment by flexiblyCode** [comment]
https://www.cnblogs.com/asplover/p/17188483.html可以看下这篇文章，挺详细的

**Comment by 21307369** [comment]
windows 打开CMD  设置用户环境变量
`setx NODE_OPTIONS --openssl-legacy-provider`
