### ISSUE TITLE
该路由对应页面的 组件 :方案2 (动态加载)

### ISSUE THREAD

**Issue by zhoulin00** [vueComponent/ant-design-vue-pro#697]
\src\router\generator-routers.js

1. 使用方案1没问题
 //该路由对应页面的 组件 :方案1
 component: constantRouterComponents[item.component || item.key], 

2. 使用方案2就启动不了
 // 该路由对应页面的 组件 :方案2 (动态加载)
component: (constantRouterComponents[item.component || item.key]) || (() => import(`@/views/${item.component}`)),

异常如下：
`
 ERROR  Failed to compile with 1 errors                                                                                            16:01:06
 error  in ./src/router/generator-routers.js

Module build failed (from ./node_modules/_eslint-loader@2.2.1@eslint-loader/index.js):
TypeError: Cannot read property 'range' of null
Occurred while linting D:\zl\work\TTTTTT\web\src\router\generator-routers.js:121
    at SourceCode.getTokenBefore (D:\zl\work\TTTTTT\web\node_modules\_eslint@5.16.0@eslint\lib\token-store\index.js:303:18)
    at checkSpacingBefore (D:\zl\work\TTTTTT\web\node_modules\_eslint@5.16.0@eslint\lib\rules\template-curly-spacing.js:60:42)       
    at TemplateElement (D:\zl\work\TTTTTT\web\node_modules\_eslint@5.16.0@eslint\lib\rules\template-curly-spacing.js:119:17)
    at D:\zl\work\TTTTTT\web\node_modules\_eslint@5.16.0@eslint\lib\util\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (D:\zl\work\TTTTTT\web\node_modules\_eslint@5.16.0@eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (D:\zl\work\TTTTTT\web\node_modules\_eslint@5.16.0@eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (D:\zl\work\TTTTTT\web\node_modules\_eslint@5.16.0@eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (D:\zl\work\TTTTTT\web\node_modules\_eslint@5.16.0@eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (D:\zl\work\TTTTTT\web\node_modules\_eslint@5.16.0@eslint\lib\code-path-analysis\code-path-analyzer.js:632:23)
    at D:\zl\work\TTTTTT\web\node_modules\_eslint@5.16.0@eslint\lib\linter.js:752:32
    at Array.forEach (<anonymous>)
    at runRules (D:\zl\work\TTTTTT\web\node_modules\_eslint@5.16.0@eslint\lib\linter.js:747:15)
    at Linter._verifyWithoutProcessors (D:\zl\work\TTTTTT\web\node_modules\_eslint@5.16.0@eslint\lib\linter.js:899:31)
    at D:\zl\work\TTTTTT\web\node_modules\_eslint@5.16.0@eslint\lib\linter.js:955:35
    at Array.map (<anonymous>)

 @ ./src/store/modules/async-router.js 8:0-68 25:8-30
 @ ./src/store/index.js
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@3.10.3@webpack-dev-server/client?http://172.16.153.55:8000/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
`
不知道为啥。

**Comment by sendya** [comment]
照着这个 commit 做
https://github.com/sendya/ant-design-pro-vue/commit/ac0bdd9fca86958ea588c8475d0e8793c91795a9
