### ISSUE TITLE
yarn run serve 错误

### ISSUE THREAD

**Issue by ycs77** [vueComponent/ant-design-vue-pro#816]
**Question （问题描述）**

发生错误的 Git hash： 5638640c8d1f7789e440920063be7953aecdd79d (branch `refactor/pro-v3`)

重现错误：

```
git clone https://github.com/vueComponent/ant-design-vue-pro.git
cd ant-design-vue-pro
yarn install
yarn run serve
```

此时返回以下错误：

```
 error  in ./src/components/SelectLang/index.less

Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: Invalid or unexpected token

(@D:\dev\code\ant-design-vue-pro\postcss.config.js)
    at load (D:\dev\code\ant-design-vue-pro\node_modules\postcss-load-config\src\plugins.js:28:11)
    at D:\dev\code\ant-design-vue-pro\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (D:\dev\code\ant-design-vue-pro\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (D:\dev\code\ant-design-vue-pro\node_modules\postcss-load-config\src\index.js:33:14)
    at D:\dev\code\ant-design-vue-pro\node_modules\postcss-load-config\src\index.js:94:14

 @ ./src/components/SelectLang/index.less 4:14-237 14:3-18:5 15:22-245
 @ ./src/components/SelectLang/index.jsx
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/GlobalHeader/RightContent.vue?vue&type=script&lang=js&
 @ ./src/components/GlobalHeader/RightContent.vue?vue&type=script&lang=js&
 @ ./src/components/GlobalHeader/RightContent.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/BasicLayout.vue?vue&type=script&lang=js&
 @ ./src/layouts/BasicLayout.vue?vue&type=script&lang=js&
 @ ./src/layouts/BasicLayout.vue
 @ ./src/layouts/index.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/account/center/index.vue?vue&type=script&lang=js&
 @ ./src/views/account/center/index.vue?vue&type=script&lang=js&
 @ ./src/views/account/center/index.vue
 @ ./src/config/router.config.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.3:8001/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Describe the solution you'd like （你期待的是什么？）**
正常运行 `yarn run serve` 不会报错

**Comment by sendya** [comment]
无法复现

**Comment by sendya** [comment]
尝试锁 less lessloader 的版本试试看

**Comment by ycs77** [comment]
删除 `yarn.lock` 再重新执行 `yarn install` 和 `yarn run serve` 就可以了，看来是依赖的版本问题。
