### ISSUE TITLE
单元测试时ant design vue组件import失败，如何配置？

### ISSUE THREAD

**Issue by Fallsleep** [vueComponent/ant-design-vue-pro#903]
**Question （问题描述）**
针对`@/view/user/Login.vue`写了个简单的`jest`单元测试，测试代码如下：
```javascript
// tests/unit/views/user/login.spec.js
import { mount } from '@vue/test-utils'
import Login from '@/views/user/Login'

describe('登录组件测试', () => {
  it('用户名密码登录渲染', () => {
    const wrapper = mount(Login)
    expect(wrapper.html()).toMatchSnapshot()
  })
})

```

`npm run test:unit`后报错：
```shell
$ npm run test:unit

> vue-antd-pro@3.0.0 test:unit D:\demo
> vue-cli-service test:unit

FAIL tests/unit/views/user/login.spec.js
  ● Test suite failed to run

    D:\demo\node_modules\ant-design-vue\es\notification\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import _extends from 'babel-runtime/helpers/extends';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      73 |
      74 | import axios from 'axios'
    > 75 | import notification from 'ant-design-vue/es/notification'
         | ^
      76 | import { VueAxios } from './axios'

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/utils/request.js:75:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.362s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-antd-pro@3.0.0 test:unit: `vue-cli-service test:unit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-antd-pro@3.0.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

看起来是`babel.config.js`中关于`ant-design-vue`的懒加载配置没有生效？或者是`es6`的`import不能正常使用？`

**Describe the solution you'd like （你期待的是什么？）**
要如何修改`babel.config.js`或其他配置文件才能正常的执行`npm run test:unit`

**Additional context（附加信息）**
无

**Comment by Fallsleep** [comment]
对`tests/unit/views/user/login.spec.js`文件进行如下修改
```js
// tests/unit/views/user/login.spec.js
import '@/core/lazy_use'
import { mount } from '@vue/test-utils'
import Login from '@/views/user/Login'

describe('登录组件测试', () => {
  it('用户名密码登录渲染', () => {
    const wrapper = mount(Login)
    expect(wrapper.html()).toMatchSnapshot()
  })
})
```

并在`jest.config.js`文件中添加以下配置后不再报`import`相关的错误：
```javascript
module.exports = {
  ...
  transformIgnorePatterns: [
    // 转译node_modules目录下的@ant-design-vue、ant-design-vue等包，其余不转译
    'node_modules/(?!(@?ant-design-vue)/)'
  ],
  ...
}
```

但是框架中内联引入了很多`svg`文件，会引发类似`Cannot find module '../assets/logo.svg?inline' from 'BasicLayout.vue'`错误。

`jest.config.js`文件中的配置似乎只能匹配不带`?inline`的`svg`引入，我尝试在`transform`中添加`'.+inline$': 'jest-transform-stub'`，依然无法处理。

这种情况要怎么配置？

**Comment by Fallsleep** [comment]
将`jest.config.js`文件的`moduleNameMapper`配置修改为：
```
    '^@/(.+\\.svg)\\?inline$': '<rootDir>/src/$1',
    '^@/(.*)$': '<rootDir>/src/$1',
    '^(.+/.*\\.svg)\\?inline$': '$1'
```
可解决`svg?inline`的问题。

现在报了一个`Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)`错误，此外`Vue`给了两个`Unknown custom element: <router-link>`警告。

**Comment by sendya** [comment]
一般写测试，不会这样测。
都是每个组件独立测试，针对组件渲染结果校验。不会整个页面跑的，不然很多依赖根本无法使用

**Comment by Fallsleep** [comment]
是指不需要`import '@/core/lazy_use'`么？

即使每个组件独立测试，但如果写复杂一些的组件呢？加载了第三方组件或者自己写的组件要如何处理？

还是说通常情况下不会对复杂的`view`进行测试？

**Comment by Fallsleep** [comment]
针对`view`中的页面或者比组件更大的模块的测试，是否应该是`e2e`测试？项目开发中`e2e`测试是否是必须的呢？ @sendya

**Comment by sendya** [comment]
如你有需要 就自己加
业务相关的问题请自己考虑
