### ISSUE TITLE
设置了publicpath为'/myapp' 路由配置要怎么更改啊？

### ISSUE THREAD

**Issue by Kimi1020** [vueComponent/ant-design-vue-pro#945]
**Question （问题描述）**

在vue.config.js 里面设置了publicPath
 publicPath: '/myapp/',

请问router.config.js 里面的asyncRouterMap 要怎么配合更改啊？

如果不改直接404页面了

感谢

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by Kimi1020** [comment]
1. 自己研究了以后在router/index.js里加了base的配置如下 
export default new Router({
  base: '/myapp',
  mode: 'history',
  routes: constantRouterMap
})

解决了上面的问题，但是如何处理path为'/'的情况？

输入localhosto:8000/ 以后报错如下：

URIError: Failed to decode param '/%3C%=%20htmlWebpackPlugin.options.cdn.css[i]%20%%3E'
    at decodeURIComponent (<anonymous>)
    at decode_param (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:172:12)
    at Layer.match (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:123:27) 
    at matchLayer (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:574:18)
    at next (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:220:15)
    at expressInit (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:95:5)
    at trim_prefix (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:317:13)
    at D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:284:7
    at Function.process_params (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:335:12)
    at next (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:275:10)
    at query (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:95:5)
    at trim_prefix (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:317:13)
    at D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:284:7
    at Function.process_params (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:335:12)
URIError: Failed to decode param '/%3C%=%20htmlWebpackPlugin.options.cdn.js[i]%20%%3E'
    at decodeURIComponent (<anonymous>)
    at decode_param (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:172:12)
    at Layer.match (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:123:27)
    at matchLayer (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:574:18)
    at next (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:220:15)
    at expressInit (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:95:5)
    at trim_prefix (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:317:13)
    at D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:284:7
    at Function.process_params (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:335:12)
    at next (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:275:10)
    at query (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:95:5)
    at trim_prefix (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:317:13)
    at D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:284:7
    at Function.process_params (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:335:12)
URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Elogo.png'
    at decodeURIComponent (<anonymous>)
    at decode_param (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:172:12)
    at Layer.match (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:123:27)
    at matchLayer (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:574:18)
    at next (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:220:15)
    at expressInit (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:95:5)
    at trim_prefix (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:317:13)
    at D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:284:7
    at Function.process_params (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:335:12)
    at next (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:275:10)
    at query (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:95:5)
    at trim_prefix (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:317:13)
    at D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:284:7
    at Function.process_params (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:335:12)
URIError: Failed to decode param '/%3C%=%20htmlWebpackPlugin.options.cdn.css[i]%20%%3E'
    at decodeURIComponent (<anonymous>)
    at decode_param (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:172:12)
    at Layer.match (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:123:27)
    at matchLayer (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:574:18)
    at next (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:220:15)
    at expressInit (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:95:5)
    at trim_prefix (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:317:13)
    at D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:284:7
    at Function.process_params (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:335:12)
    at next (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:275:10)
    at query (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:95:5)
    at trim_prefix (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:317:13)
    at D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:284:7
    at Function.process_params (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:335:12)
URIError: Failed to decode param '/%3C%=%20htmlWebpackPlugin.options.cdn.js[i]%20%%3E'
    at decodeURIComponent (<anonymous>)
    at decode_param (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:172:12)
    at Layer.match (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:123:27)
    at matchLayer (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:574:18)
    at next (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:220:15)
    at expressInit (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:95:5)
    at trim_prefix (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:317:13)
    at D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:284:7
    at Function.process_params (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:335:12)
    at next (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:275:10)
    at query (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:95:5)
    at trim_prefix (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:317:13)
    at D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:284:7
    at Function.process_params (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:335:12)
URIError: Failed to decode param '/%3C%=%20htmlWebpackPlugin.options.cdn.js[i]%20%%3E'
    at decodeURIComponent (<anonymous>)
    at decode_param (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:172:12)
    at Layer.match (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:123:27)
    at matchLayer (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:574:18)
    at next (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:220:15)
    at expressInit (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:95:5)
    at trim_prefix (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:317:13)
    at D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:284:7
    at Function.process_params (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:335:12)
    at next (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:275:10)
    at query (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:95:5)
    at trim_prefix (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:317:13)
    at D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:284:7
    at Function.process_params (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:335:12)
URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Elogo.png'
    at decodeURIComponent (<anonymous>)
    at decode_param (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:172:12)
    at Layer.match (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:123:27)
    at matchLayer (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:574:18)
    at next (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:220:15)
    at expressInit (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:95:5)
    at trim_prefix (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:317:13)
    at D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:284:7
    at Function.process_params (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:335:12)
    at next (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:275:10)
    at query (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\layer.js:95:5)
    at trim_prefix (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:317:13)
    at D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:284:7
    at Function.process_params (D:\workspace\Indexsupportsystem\node_modules\_express@4.17.1@express\lib\router\index.js:335:12)
